services:
  frontend:
    build: ./frontend
    container_name: react_web
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.deployment
    depends_on:
      - api
  api:
    build: ./backend
    container_name: fastapi_app
    # command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload & while ! curl -s http://localhost:8000/docs > /dev/null; do echo 'Waiting for API...'; sleep 2; done; tail -f /dev/null"
    # command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload & while ! curl -s http://localhost:8000/docs > /dev/null; do echo 'Waiting for API...'; sleep 2; done; python /app/app/api_simulation.py && tail -f /dev/null"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app