services:
  api:
    build: ./backend
    container_name: fastapi_app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
  # web:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"