name: Build and Deploy to Azure Container Registry (ACR)

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: ssdbackend
  CONTAINER_APP_NAME: ssdbackend
  RESOURCE_GROUP: SSDBackend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Build and push backend Docker image to ACR
      uses: docker/build-push-action@v6
      with:
        context: ./backend  # 設定 Dockerfile 路徑所在的目錄
        file: ./backend/Dockerfile  # 指定 Dockerfile 路徑
        push: true  # 自動推送到 ACR
        tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}  # 設定推送的映像名稱

    # - name: Build and push frontend Docker image to ACR
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: ./frontend  # 設定前端的 Dockerfile 路徑
    #     file: ./frontend/Dockerfile  # 指定前端 Dockerfile 路徑
    #     push: true  # 自動推送到 ACR
    #     tags: myregistry.azurecr.io/react-web:v1  # 設定推送的映像名稱

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS}}
    
    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        environmentVariables: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          SECRET_KEY=${{ secrets.SECRET_KEY}}
          FASTAPI_ENVIRONMENT=Development

    # 6. 可選：發送成功消息
    - name: Notify success
      run: echo "Docker images successfully pushed to ACR!"