name: Trigger auto deployment for ssdbackend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ssdbackend-AutoDeployTrigger-d5943ed0-ca12-4e3a-bc29-f927b7ee83bc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SSDBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SSDBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SSDBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ssdbackend.azurecr.io
          registryUsername: ${{ secrets.SSDBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SSDBACKEND_REGISTRY_PASSWORD }}
          containerAppName: ssdbackend
          resourceGroup: SSDBackend
          imageToBuild: ssdbackend.azurecr.io/ssdbackend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


